version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  springboot-app:
    image: vikasespire/springboot:0.0.4
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mobilemodel

  angular-app:
    image: vikasespire/angular:0.0.7
    container_name: angular-app
    ports:
      - "4200:80"   # If using Angular CLI inside nginx image, map to 80
    depends_on:
      - springboot-app
    environment:
      - API_BASE_URL=http://springboot-app:8080

volumes:
  mongo_data:

