version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: springboot-app
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: angular-app
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
